### PR TITLE
image changes to under 100k

### PR DESCRIPTION
**Pull request by shakersinthedark**

### CODE REVIEW

**Comment by alexlbr** [comment]
@shakersinthedark I've tried some of the images randomly like https://firebasestorage.googleapis.com/v0/b/reactjsacademy-react.appspot.com/o/part-time.jpg?alt=media and they don't load. Are the urls correct?

**Comment by shakersinthedark** [comment]
@alexlbr So this is a problem with naming because I named all my images one thing and when the site was developed, the images were sometimes called something else. I've visually checked the images locally and everything works - I would delete the duplications but that'd delete them on the live site!

**Comment by shakersinthedark** [comment]
@alexlbr I'll double check them again in a but and confirm with you all the images are correct

**Comment by shakersinthedark** [comment]
@alexlbr i've reviewed all the images, everything seems to work. Once this has merged, I will audit the firebase storage for unused images and delete them and will also look to organise everything better.

**Comment by shakersinthedark** [comment]
@alexlbr I've sorted the conflicts but i have no idea what's going on with the CircleCI failure :(

**Pull request merged**
